# Beispiel docker-compose.yml für Anmeldung Pro MMBbS
# Der Ordner ./config enthält secrets.json und weitere Konfigurationsdateien und wird als Volume in den Container gemountet.
version: '3.8'
services:
  anmeldung:
    build: .
    container_name: tuttas/anmeldung_prommbbs
    ports:
      - "4000:4000"
    volumes:
      - ./config:/app/config:ro
    environment:
      - CONFIG_DIR=/app/config
